worker_processes auto;
pid /var/run/nginx.pid;

events {
    worker_connections 4096;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    server_tokens off;
    sendfile      on;
    tcp_nopush    on;
    keepalive_timeout 65;

    log_format json escape=json '{"time":"$time_iso8601","remote":"$remote_addr",'
        '"method":"$request_method","uri":"$request_uri","status":$status,'
        '"bytes":$body_bytes_sent,"duration":$request_time,"cache":"$upstream_cache_status",'
        '"request_id":"$ct_request_id","ua":"$http_user_agent"}';
    access_log /dev/stdout json;
    error_log  /dev/stderr warn;

    gzip on;
    gzip_comp_level 5;
    gzip_min_length 512;
    gzip_vary on;
    gzip_proxied any;
    gzip_types text/css application/javascript application/json image/svg+xml text/plain;

    # Docker-DNS, zodat nginx `api` opnieuw opzoekt als die container een nieuw IP krijgt.
    resolver 127.0.0.11 valid=10s ipv6=off;

    include /etc/nginx/conf.d/*.conf;
}
