# Minimale type-stubs voor tinycss2.serializer; zie ast.pyi.

from collections.abc import Iterable

from tinycss2.ast import Node

BAD_PAIRS: set[tuple[str, str]]

def serialize(nodes: Iterable[Node]) -> str: ...
def serialize_identifier(value: str) -> str: ...
def serialize_string_value(value: str) -> str: ...
def serialize_url(value: str) -> str: ...
