"""initial schema

MVP-tabellen uit docs/03-database-ontwerp.md, plus:
- extensie pg_trgm (autocomplete op selectors);
- triggers die theme_versions onveranderlijk en audit_logs append-only maken.

Revision ID: 0001
Revises:
Create Date: 2026-10-05 13:01:36.888920
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


ENUMS = (
    "user_role",
    "job_type",
    "job_status",
    "service_type",
    "service_source",
    "page_kind",
    "snapshot_origin",
    "theme_status",
    "selector_kind",
    "version_source",
)

IMMUTABILITY_SQL = (
    """
CREATE FUNCTION cssthema_forbid_change() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF current_setting('cssthema.allow_mutation', true) = 'on' THEN
        RETURN COALESCE(NEW, OLD);
    END IF;
    RAISE EXCEPTION '% on % is not allowed (immutable table)', TG_OP, TG_TABLE_NAME
        USING ERRCODE = 'insufficient_privilege';
END;
$$
""",
    """
CREATE TRIGGER theme_versions_immutable
    BEFORE UPDATE ON theme_versions
    FOR EACH ROW EXECUTE FUNCTION cssthema_forbid_change()
""",
    """
CREATE TRIGGER audit_logs_append_only
    BEFORE UPDATE OR DELETE ON audit_logs
    FOR EACH ROW EXECUTE FUNCTION cssthema_forbid_change()
""",
)


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assets",
        sa.Column("storage_key", sa.String(length=512), nullable=False),
        sa.Column("content_type", sa.String(length=127), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("sha256", sa.LargeBinary(length=32), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assets")),
        sa.UniqueConstraint("sha256", name=op.f("uq_assets_sha256")),
        sa.UniqueConstraint("storage_key", name=op.f("uq_assets_storage_key")),
    )
    op.create_table(
        "users",
        sa.Column("oidc_subject", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("role", sa.Enum("admin", "editor", "viewer", name="user_role"), nullable=False),
        sa.Column("role_override", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("oidc_subject", name=op.f("uq_users_oidc_subject")),
    )
    op.create_table(
        "api_keys",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("prefix", sa.String(length=16), nullable=False),
        sa.Column("secret_hash", sa.LargeBinary(length=32), nullable=False),
        sa.Column("scopes", sa.ARRAY(sa.String(length=40)), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_api_keys_user_id_users"), ondelete="CASCADE"
        ),
        sa.CheckConstraint(
            "scopes <@ ARRAY['themes:read', 'themes:write', 'themes:publish', 'services:read', "
            "'services:write', 'discovery:run', 'ai:generate', 'audit:read']::varchar[]",
            name=op.f("ck_api_keys_scopes_allowed"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_keys")),
        sa.UniqueConstraint("prefix", name=op.f("uq_api_keys_prefix")),
    )
    op.create_index(
        "ix_api_keys_user_active",
        "api_keys",
        ["user_id"],
        unique=False,
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    op.create_table(
        "jobs",
        sa.Column(
            "type",
            sa.Enum(
                "snapshot_capture",
                "snapshot_analyze",
                "screenshot_capture",
                "discovery_npm",
                "discovery_urls",
                "ai_generate",
                "theme_health_check",
                "export_bundle",
                "maintenance",
                name="job_type",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("queued", "running", "succeeded", "failed", "cancelled", name="job_status"),
            nullable=False,
        ),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("progress", sa.SmallInteger(), nullable=False),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_jobs_created_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
    )
    op.create_index("ix_jobs_created_by", "jobs", ["created_by", "created_at"], unique=False)
    op.create_index("ix_jobs_status_created", "jobs", ["status", "created_at"], unique=False)
    op.create_table(
        "palettes",
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("tokens", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_builtin", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_palettes_created_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_palettes")),
    )
    op.create_index(
        "uq_palettes_slug_active",
        "palettes",
        ["slug"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "services",
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "generic",
                "proxmox",
                "nextcloud",
                "immich",
                "home_assistant",
                "grafana",
                "unifi",
                "jellyfin",
                "authentik",
                "uptime_kuma",
                "portainer",
                name="service_type",
            ),
            nullable=False,
        ),
        sa.Column("base_url", sa.String(length=2048), nullable=False),
        sa.Column("login_url", sa.String(length=2048), nullable=True),
        sa.Column("favicon_asset_id", sa.Uuid(), nullable=True),
        sa.Column(
            "source",
            sa.Enum("manual", "npm", "url_list", "import", name="service_source"),
            nullable=False,
        ),
        sa.Column("npm_proxy_host_id", sa.Integer(), nullable=True),
        sa.Column("tags", sa.ARRAY(sa.String(length=40)), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("last_crawled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["favicon_asset_id"],
            ["assets.id"],
            name=op.f("fk_services_favicon_asset_id_assets"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_services")),
    )
    op.create_index("ix_services_tags", "services", ["tags"], unique=False, postgresql_using="gin")
    op.create_index(
        "uq_services_base_url_active",
        "services",
        ["base_url"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "uq_services_slug_active",
        "services",
        ["slug"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "settings",
        sa.Column("key", sa.String(length=120), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("encrypted_value", sa.LargeBinary(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"], ["users.id"], name=op.f("fk_settings_updated_by_users")
        ),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_settings")),
    )
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column(
            "at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("actor_api_key_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=80), nullable=False),
        sa.Column("entity_type", sa.String(length=40), nullable=True),
        sa.Column("entity_id", sa.Uuid(), nullable=True),
        sa.Column("ip", postgresql.INET(), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("changes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_api_key_id"],
            ["api_keys.id"],
            name=op.f("fk_audit_logs_actor_api_key_id_api_keys"),
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"], ["users.id"], name=op.f("fk_audit_logs_actor_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    op.create_index(
        "ix_audit_logs_actor",
        "audit_logs",
        ["actor_user_id", sa.literal_column("at DESC")],
        unique=False,
    )
    op.create_index("ix_audit_logs_at", "audit_logs", [sa.literal_column("at DESC")], unique=False)
    op.create_index(
        "ix_audit_logs_entity",
        "audit_logs",
        ["entity_type", "entity_id", sa.literal_column("at DESC")],
        unique=False,
    )
    op.create_table(
        "dom_snapshots",
        sa.Column("service_id", sa.Uuid(), nullable=False),
        sa.Column(
            "page_kind", sa.Enum("home", "login", "custom", name="page_kind"), nullable=False
        ),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column("final_url", sa.String(length=2048), nullable=True),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column(
            "origin",
            sa.Enum("crawler", "url_import", "upload", name="snapshot_origin"),
            nullable=False,
        ),
        sa.Column("document_asset_id", sa.Uuid(), nullable=True),
        sa.Column("html_sha256", sa.LargeBinary(length=32), nullable=True),
        sa.Column("title", sa.String(length=500), nullable=True),
        sa.Column("css_variables", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("components", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("framework_hints", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("stylesheets", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("colors", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("class_count", sa.Integer(), nullable=False),
        sa.Column("id_count", sa.Integer(), nullable=False),
        sa.Column("has_shadow_dom", sa.Boolean(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["document_asset_id"],
            ["assets.id"],
            name=op.f("fk_dom_snapshots_document_asset_id_assets"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_dom_snapshots_job_id_jobs"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["services.id"],
            name=op.f("fk_dom_snapshots_service_id_services"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dom_snapshots")),
    )
    op.create_index(
        "ix_dom_snapshots_latest",
        "dom_snapshots",
        ["service_id", "page_kind", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "themes",
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("service_id", sa.Uuid(), nullable=True),
        sa.Column("palette_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status", sa.Enum("draft", "published", "archived", name="theme_status"), nullable=False
        ),
        sa.Column("draft_css", sa.Text(), nullable=False),
        sa.Column("draft_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("draft_updated_by", sa.Uuid(), nullable=True),
        sa.Column("published_version_id", sa.Uuid(), nullable=True),
        sa.Column("latest_version_number", sa.Integer(), nullable=False),
        sa.Column("lock_version", sa.Integer(), nullable=False),
        sa.Column("tags", sa.ARRAY(sa.String(length=40)), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "slug ~ '^[a-z0-9][a-z0-9-]{0,62}[a-z0-9]$'", name=op.f("ck_themes_slug_format")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_themes_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["draft_updated_by"], ["users.id"], name=op.f("fk_themes_draft_updated_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["palette_id"],
            ["palettes.id"],
            name=op.f("fk_themes_palette_id_palettes"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["services.id"],
            name=op.f("fk_themes_service_id_services"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_themes")),
    )
    op.create_index(
        "ix_themes_service_active",
        "themes",
        ["service_id"],
        unique=False,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "uq_themes_slug_active",
        "themes",
        ["slug"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "snapshot_selectors",
        sa.Column("snapshot_id", sa.Uuid(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("class", "id", "css_variable", "element", "attribute", name="selector_kind"),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=512), nullable=False),
        sa.Column("occurrences", sa.Integer(), nullable=False),
        sa.Column("in_shadow_dom", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["dom_snapshots.id"],
            name=op.f("fk_snapshot_selectors_snapshot_id_dom_snapshots"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("snapshot_id", "kind", "name", name=op.f("pk_snapshot_selectors")),
    )
    op.create_index(
        "ix_snapshot_selectors_name_trgm",
        "snapshot_selectors",
        ["name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.create_table(
        "theme_versions",
        sa.Column("theme_id", sa.Uuid(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("css_source", sa.Text(), nullable=False),
        sa.Column("css_compiled", sa.Text(), nullable=False),
        sa.Column("sha256", sa.LargeBinary(length=32), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column(
            "source",
            sa.Enum("manual", "rollback", "import", "duplicate", "ai", name="version_source"),
            nullable=False,
        ),
        sa.Column("source_version_id", sa.Uuid(), nullable=True),
        sa.Column("palette_id", sa.Uuid(), nullable=True),
        sa.Column("palette_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("message", sa.String(length=500), nullable=True),
        sa.Column("lint_warnings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_theme_versions_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["palette_id"],
            ["palettes.id"],
            name=op.f("fk_theme_versions_palette_id_palettes"),
        ),
        sa.ForeignKeyConstraint(
            ["source_version_id"],
            ["theme_versions.id"],
            name=op.f("fk_theme_versions_source_version_id_theme_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["theme_id"],
            ["themes.id"],
            name=op.f("fk_theme_versions_theme_id_themes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_theme_versions")),
        sa.UniqueConstraint("theme_id", "version_number", name="uq_theme_versions_theme_version"),
    )
    # ### end Alembic commands ###

    # Circulaire FK themes.published_version_id -> theme_versions pas na beide tabellen.
    op.create_foreign_key(
        "fk_themes_published_version_id",
        "themes",
        "theme_versions",
        ["published_version_id"],
        ["id"],
        ondelete="SET NULL",
    )
    for statement in IMMUTABILITY_SQL:
        op.execute(statement)


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS audit_logs_append_only ON audit_logs")
    op.execute("DROP TRIGGER IF EXISTS theme_versions_immutable ON theme_versions")
    op.execute("DROP FUNCTION IF EXISTS cssthema_forbid_change()")
    op.drop_constraint("fk_themes_published_version_id", "themes", type_="foreignkey")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("theme_versions")
    op.drop_index(
        "ix_snapshot_selectors_name_trgm",
        table_name="snapshot_selectors",
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.drop_table("snapshot_selectors")
    op.drop_index(
        "uq_themes_slug_active", table_name="themes", postgresql_where=sa.text("deleted_at IS NULL")
    )
    op.drop_index(
        "ix_themes_service_active",
        table_name="themes",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_table("themes")
    op.drop_index("ix_dom_snapshots_latest", table_name="dom_snapshots")
    op.drop_table("dom_snapshots")
    op.drop_index("ix_audit_logs_entity", table_name="audit_logs")
    op.drop_index("ix_audit_logs_at", table_name="audit_logs")
    op.drop_index("ix_audit_logs_actor", table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_table("settings")
    op.drop_index(
        "uq_services_slug_active",
        table_name="services",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index(
        "uq_services_base_url_active",
        table_name="services",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index("ix_services_tags", table_name="services", postgresql_using="gin")
    op.drop_table("services")
    op.drop_index(
        "uq_palettes_slug_active",
        table_name="palettes",
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_table("palettes")
    op.drop_index("ix_jobs_status_created", table_name="jobs")
    op.drop_index("ix_jobs_created_by", table_name="jobs")
    op.drop_table("jobs")
    op.drop_index(
        "ix_api_keys_user_active",
        table_name="api_keys",
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    op.drop_table("api_keys")
    op.drop_table("users")
    op.drop_table("assets")
    # ### end Alembic commands ###
    for enum_name in ENUMS:
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
